[package]
name = "arr-upgrade"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
arr-api = { path = "../arr-api/" }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
toml = "1.1.6"

[dev-dependencies]
tempfile = "3.27.0"
