[package]
name = "arr-api"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13.5", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", default-features = false }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["time"] }
